exports.writePost = `INSERT INTO posts (writer_id, category_id, title, content) VALUES (?,?,?,?)`;
exports.writeLinks = `INSERT INTO links (post_id, link) VALUES ?`;
exports.getPosts = `SELECT * FROM posts WHERE writer_id = ?`;
exports.getAllPosts = `SELECT * FROM posts`;
exports.getPostsBySearch = `SELECT * FROM posts WHERE title LIKE ?`;
exports.getPostsByCategory = `SELECT * FROM posts WHERE category_id =?`;
exports.limitOffset = ` LIMIT ? OFFSET ?`;
exports.getPostWriterById = `SELECT * FROM users WHERE id = ?`;
exports.getTotalComments = `SELECT COUNT(*) as count FROM comments WHERE post_id = ?`;
exports.deletePost = `DELETE FROM posts WHERE id =?`;
exports.getPostById = `SELECT * FROM posts WHERE id = ?`;
exports.getCommentsByPostId = `SELECT * FROM comments WHERE post_id = ?`;
exports.getUserById = `SELECT * FROM users WHERE id = ?`;
exports.getLinksByPostId = `SELECT * FROM links WHERE post_id =?`;
exports.countQuery = `SELECT COUNT(*) AS total FROM posts`;
exports.getPostWriter = `SELECT writer_id FROM posts WHERE id = ?`;
exports.updatePost = `UPDATE posts SET category_id = ?, title = ?, content = ? WHERE id = ?`;
exports.deleteLinks = `DELETE FROM links WHERE post_id = ?`;

exports.getScrapList = `SELECT post_id FROM scraps WHERE user_id = ?`;
exports.getScrapPosts = `SELECT id as postId, title, category_id as categoryId, created_at as createdAt FROM posts WHERE id IN (?)`;
exports.scrap = `INSERT INTO scraps (post_id, user_id) VALUES (?, ?)`;
exports.getScrapCount = `SELECT COUNT(*) as count FROM scraps WHERE post_id = ? AND user_id = ?`;
exports.deleteScrap = `DELETE FROM scraps WHERE user_id = ? AND post_id = ?`;
